name: CI/CD Pipeline for Book Hive App

on:
  push: 
    branches:
      - master
    
  pull_request:
    branches:
      - master


jobs:
  build-deploy:
    name: Build and Deploy Book Hive Web App
    runs-on: ubuntu-latest

    steps:
      # 1. Checking out the code - Github actions will copy the code from the Github repo and clone it into the runner.
      - name: Checkout Code
        uses: actions/checkout@v4 # actions that want to be run

      # 2. Setup environment in the runner machine
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run the Tests
      # - name: Run Tests
      # run: if any command to run the test files specify here

      # 5. Packaging the application
      # - name: Build and Package the application
